In [6]:
import numpy as np

In [7]:
n1 = np.array([[6, 7, 2, 4, 21], [72, 2, 9, 92, 11], [3, 4, 6, 7, 5]])
n1

array([[ 6,  7,  2,  4, 21],
       [72,  2,  9, 92, 11],
       [ 3,  4,  6,  7,  5]])

In [8]:
n2 = np.array([[1, 2, 4, 7], [63, 27, 86, 29], [3, 2, 7,62]])
n2.shape

(3, 4)

In [9]:
n3 = np.zeros((2,4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
n4 = np.full((2, 3),27)
n4

array([[27, 27, 27],
       [27, 27, 27]])

In [11]:
n5 = np.arange(1, 555, 5)
n5

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196, 201, 206, 211, 216, 221, 226, 231, 236, 241, 246, 251, 256,
       261, 266, 271, 276, 281, 286, 291, 296, 301, 306, 311, 316, 321,
       326, 331, 336, 341, 346, 351, 356, 361, 366, 371, 376, 381, 386,
       391, 396, 401, 406, 411, 416, 421, 426, 431, 436, 441, 446, 451,
       456, 461, 466, 471, 476, 481, 486, 491, 496, 501, 506, 511, 516,
       521, 526, 531, 536, 541, 546, 551])

In [12]:
n6 = np.random.randint(10, 50, 49)
n6

array([39, 48, 39, 44, 16, 41, 32, 26, 40, 25, 22, 31, 22, 13, 34, 13, 43,
       33, 18, 35, 37, 49, 47, 23, 46, 31, 23, 16, 33, 45, 41, 29, 15, 18,
       33, 11, 12, 11, 49, 22, 20, 45, 15, 15, 21, 37, 17, 22, 25])

In [13]:
a = np.array([5, 8, 22])
b = np.array([2, 44, 6])

In [14]:
n7 = np.vstack((a, b))
n7

array([[ 5,  8, 22],
       [ 2, 44,  6]])

In [15]:
n8 = np.hstack((a, b))
n8

array([ 5,  8, 22,  2, 44,  6])

In [16]:
n9 = np.column_stack((a, b))
n9

array([[ 5,  2],
       [ 8, 44],
       [22,  6]])

In [17]:
k = np.array([7, 8, 9, 2, 43])
r = np.array([1, 3, 5, 11, 4])
n10 = np.sum([k, r], axis = 0)
n11 = np.sum([k, r], axis = 1)

In [37]:
n10

array([ 8, 11, 14, 13, 47])

In [39]:
n11

array([69, 24])

In [18]:
strnp = np.save('An_array', k) 

In [19]:
ak = np.load('An_array.npy')

In [20]:
ak

array([ 7,  8,  9,  2, 43])