In [1]:
import numpy as np

In [9]:
n1 = np.array([[1, 2, 4, 7], [63, -27, 86, 29], [-3, 2, -7,62], [43, 643, 986, -11]])
n1.shape
n1

array([[  1,   2,   4,   7],
       [ 63, -27,  86,  29],
       [ -3,   2,  -7,  62],
       [ 43, 643, 986, -11]])

In [25]:
n2 = np.arange(1, 100, 4)
n2

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [37]:
n3 = np.array([1, 43, 14])
n4 = np.array([98, 65, 2])
n5 = n3 * 7
n6 = n4 *3

In [41]:
print(f'n5:{n5}, \n n6:{n6}')

n5:[  7 301  98], 
 n6:[294 195   6]


In [51]:
n7 = np.random.randint(10, 111, 66)
n7

array([ 18,  36,  10,  76,  41,  16,  42,  71,  14,  22,  65,  25,  42,
       100,  63,  63,  47,  89,  77,  73, 110,  64, 110,  50,  13,  22,
        93,  34,  88,  87,  81,  90,  45,  97,  48,  58,  55,  38,  49,
        88,  71,  47,  99, 103,  41,  46,  82,  36, 100,  13,  40,  69,
        89,  30,  88,  94,  18,  66,  86,  35,  94,  24,  67,  55,  80,
        59])